---
featured: true
date: '{{ .Date.Format "2006-01-02" }}'
description: |
  Brief description of the project in Markdown.
media: 
  - content: "example1.png"
    alt_text: "Descriptive alt text for example1.png"
  - content: "example2.png"
    alt_text: "Descriptive alt text for example2.png"
---