# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sean Brynjólfsson
email: smb459@cornell.edu
description: >-
  Sean Brynjólfsson is a senior at Cornell University, College of Engineering '25.
  These are his undergraduate research projects in graphics, computer vision, robotics, and digital twins.
baseurl: ""
url: "https://jolfss.github.io"
twitter_username: "jolfss"
github_username: "jolfss"
linkedin_username: "jolfss"

#SEO
meta_keywords: "computer graphics, robotics, simulation, Cornell University, AI, autonomous systems, digital twins, computer vision"

author:
  name: "Sean Brynjólfsson"
  email: "smb459@cornell.edu"
  url: "https://jolfss.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
theme: minima

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
