baseURL = 'https://jolfss.github.io/'
languageCode = 'en-us'
title = "Sean Brynjolfsson"
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[permalinks]
  blog = '/blog/:slug/'
  papers = '/papers/:slug/'
  projects = '/projects/:slug/'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    style = 'github'
    tabWidth = 4
