#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = REPO_ROOT / "data" / "redactionbench" / "source.json"
OUTPUT_PATH = REPO_ROOT / "assets" / "js" / "redactionbench-data.js"
DEFAULT_REDACTIONBENCH_SRC = Path("/Users/sbrynjolfson/a10/pii-redaction/src")


Span = tuple[int, int]


def normalize_spans(spans: list[Any]) -> list[Span]:
    out: list[Span] = []
    for span in spans:
        if isinstance(span, dict):
            start = span.get("start")
            end = span.get("end")
        else:
            start = span[0]
            end = span[1]
        start_i = int(start)
        end_i = int(end)
        if end_i > start_i:
            out.append((start_i, end_i))
    return sorted(set(out), key=lambda item: (item[0], item[1]))


def merge_spans(spans: list[Span]) -> list[Span]:
    ordered = normalize_spans(spans)
    if not ordered:
        return []
    out = [ordered[0]]
    for start, end in ordered[1:]:
        prev_start, prev_end = out[-1]
        if start <= prev_end:
            out[-1] = (prev_start, max(prev_end, end))
        else:
            out.append((start, end))
    return out


def subtract_spans(left: list[Span], right: list[Span]) -> list[Span]:
    left_ordered = normalize_spans(left)
    right_merged = merge_spans(right)
    if not right_merged:
        return left_ordered
    out: list[Span] = []
    right_index = 0
    for left_start, left_end in left_ordered:
        cursor = left_start
        while right_index < len(right_merged) and right_merged[right_index][1] <= cursor:
            right_index += 1
        check_index = right_index
        while check_index < len(right_merged) and right_merged[check_index][0] < left_end:
            right_start, right_end = right_merged[check_index]
            if right_start > cursor:
                out.append((cursor, min(left_end, right_start)))
            cursor = max(cursor, right_end)
            if cursor >= left_end:
                break
            check_index += 1
        if cursor < left_end:
            out.append((cursor, left_end))
    return out


def span_dicts(spans: list[Span]) -> list[dict[str, int]]:
    return [{"start": int(start), "end": int(end)} for start, end in normalize_spans(spans)]


def prepare_record(record: dict[str, Any], *, kind: str) -> dict[str, Any]:
    hard = normalize_spans([span for span in record["spans"] if span[2] == "mandatory"])
    contextual = normalize_spans([span for span in record["spans"] if span[2] == "contextual"])
    combinators = normalize_spans(
        effective_yellow_combinator_spans(hard, contextual, text=record["text"])
    )
    display_contextual = subtract_spans(contextual, combinators)
    out: dict[str, Any] = {
        "text": record["text"],
        "hard": span_dicts(hard),
        "contextual": span_dicts(contextual),
        "displayContextual": span_dicts(display_contextual),
        "combinators": span_dicts(combinators),
    }
    if kind == "gallery":
        out.update(
            {
                "category": record["category"],
                "genre": record["genre"],
                "meta": record["meta"],
                "source": record.get("source"),
            }
        )
    return out


def write_js(data: dict[str, Any]) -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(data, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    OUTPUT_PATH.write_text(
        "// Generated by scripts/generate-redactionbench-data.py. Do not edit by hand.\n"
        f"globalThis.__REDACTIONBENCH_DATA__ = {payload};\n",
        encoding="utf-8",
    )


redactionbench_src = Path(os.environ.get("REDACTIONBENCH_SRC", DEFAULT_REDACTIONBENCH_SRC))
if redactionbench_src.exists():
    sys.path.insert(0, str(redactionbench_src))

try:
    from redactionlib._evaluation._metrics import effective_yellow_combinator_spans
except ModuleNotFoundError as exc:
    raise SystemExit(
        "Could not import redactionlib._evaluation._metrics. "
        "Set REDACTIONBENCH_SRC to the RedactionBench src directory."
    ) from exc


def main() -> int:
    source = json.loads(SOURCE_PATH.read_text(encoding="utf-8"))
    generated = {
        "gallerySamples": [
            prepare_record(record, kind="gallery")
            for record in source["gallerySamples"]
        ],
        "demo": prepare_record(source["demo"], kind="demo"),
    }
    write_js(generated)
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
